#use_nerdfont=true
flip_status_indicators=true
#initial_screen="cover"


[theme]
error_bg="#FF296a"
playing="#3DFBAC"
#playing_bg="#FFFFFF"
playing_selected="#000000"

title="#3DFBAC"
secondary="#3DFBAC"
highlight="#000000"
highlight_bg="#3DFBAC"
statusbar_progress="#3DFBAC"
statusbar="#3DFBAC"
search_match="red"

#cmdline_bg="blue"
